### Generated by Mistlarium - The main sequence star

import PIL.Image as ewr23we90q87n34y5v6 #line:11253
so9e7nv5ygt =ewr23we90q87n34y5v6 .open (r'.\input.png')#line:367887
oa97w46b5vy =ewr23we90q87n34y5v6 .new ('RGB',(0x0780 ,0x0438 ),(0xff ,0xff ,0xff ))#line:4786786
def sert457nvhy609tp (OO00O00O00O0O00O0 ,O00OO00O0OOOOOO00 ,O000O00000O0O00O0 ,O000OOOOOOOOO00O0 ):#line:98146
    for OOO0OO00O0O0O00O0 in range (O000O00000O0O00O0 ):#line:84531
        for OOO0OOO000OOO00O0 in range (O000O00000O0O00O0 ):#line:978374
            O000OOOOOOOOO00O0 .putpixel ((OO00O00O00O0O00O0 *O000O00000O0O00O0 +OOO0OOO000OOO00O0 ,O00OO00O0OOOOOO00 *O000O00000O0O00O0 +OOO0OO00O0O0O00O0 ),(0x00 ,0x00 ,0x00 ))#line:10987
    return O000OOOOOOOOO00O0 ;#line:117465
for IlIlIIlIlIlIIIlll in range (0x21 ):#line:135678578
    for jJJjJJJjJ0O000O0OOOOO0OO in range (0x21 ):#line:1467773
        if so9e7nv5ygt .getpixel ((jJJjJJJjJ0O000O0OOOOO0OO *0x0a ,IlIlIIlIlIlIIIlll *0x0a ))==(0x00 ,0x00 ,0x00 ):#line:15457
            sert457nvhy609tp ((jJJjJJJjJ0O000O0OOOOO0OO +IlIlIIlIlIlIIIlll *0x21 )%0x30 ,(jJJjJJJjJ0O000O0OOOOO0OO +IlIlIIlIlIlIIIlll *0x21 )//0x30 ,0x28 ,oa97w46b5vy )#line:167867
oa97w46b5vy .save (r'.\output.png')